
package com.example.aarambh.ui.activities;


import android.content.Intent;
import android.os.Bundle;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;
import androidx.lifecycle.ViewModelProvider;

import com.example.aarambh.R;
import com.example.aarambh.databinding.ActivityMainBinding;
import com.example.aarambh.ui.utils.CustomProgressBar;
import com.example.aarambh.viewmodel.AuthViewModel;

public class MainActivity extends AppCompatActivity {
    ActivityMainBinding binding ;
    private AuthViewModel authViewModel;
    CustomProgressBar progressBar;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Use the correct binding class generated by data binding
        progressBar =new  CustomProgressBar();
        binding = DataBindingUtil.setContentView(this,R.layout.activity_main);
        binding.setLifecycleOwner(this);

        // Initialize ViewModel
        authViewModel = new ViewModelProvider(this).get(AuthViewModel.class);
        authViewModel.setProgressBar(progressBar);

        // Observe User Response
        authViewModel.getUserResponse().observe(this, userCheckResponse -> {
            // Handle API success response
            Toast.makeText(MainActivity.this,"User Exists: " + userCheckResponse.getMessage(),Toast.LENGTH_SHORT).show();
        });

        // Observe Error Message
        authViewModel.getErrorMessage().observe(this, error -> {
            // Handle API failure
            Toast.makeText(MainActivity.this,"Error: " + error,Toast.LENGTH_SHORT).show();
        });

        // Button Click Listener
        binding.continueButton.setOnClickListener(v -> {
            String mobile = binding.mobileInput.getText().toString().trim();
            if (!mobile.isEmpty()) {
                authViewModel.checkUser(MainActivity.this,mobile);
            } else {
//                Toast.makeText(MainActivity.this,"Please Enter Mobile Number",Toast.LENGTH_SHORT).show();
                Intent intent = new Intent(MainActivity.this,LoginActivity.class);
                startActivity(intent);
            }
        });
    }

}
