
package com.example.aarambh.activities;


import android.content.Intent;
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;

import com.example.aarambh.R;
import com.example.aarambh.databinding.ActivityMainBinding;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Use the correct binding class generated by data binding
        ActivityMainBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_main);

        // Set up click listener for the sign-up text
        binding.signUpText2.setOnClickListener(v -> {


            // Navigate to SignUp Activity
            Intent intent = new Intent(MainActivity.this, SignUpActivity.class);
            startActivity(intent);
        });
        binding.continueButton.setOnClickListener(view -> {
            Intent intent =new Intent(MainActivity.this, LoginActivity.class);
            startActivity(intent);
        });
    }
}
